import Footer from '@components/Footer'
import Header from '@components/Header'
import '@style/globals.css'
export const metadata = {
  title: 'Power Gym',
  description: 'Generated by Next.js',

}

 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body className='dark'>
        <Header/>
        <main >
        {children}
        </main>
        <Footer/>
        </body>
    </html>
  )
}
